// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtdkpfxdbktemrvhgskq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0ZGtwZnhkYmt0ZW1ydmhnc2txIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0Mjc5OTgsImV4cCI6MjA3NDAwMzk5OH0.LGM_PNg4uq61-UsnBsw4I6_oX4kjIuPxfiV9smCVGlk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});